repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.274
    hooks:
      - id: ruff
        args:
          - --fix
  - hooks:
      - args: [--safe, --quiet]
        files: ^((pyisyox|examples)/.+)?[^/]+\.py$
        id: black
    repo: https://github.com/psf/black
    rev: 23.3.0
  - hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args: [--toml, pyproject.toml]
    repo: https://github.com/codespell-project/codespell
    rev: v2.2.5

  - hooks:
      - id: isort
    repo: https://github.com/PyCQA/isort
    rev: 5.12.0

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=main
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python3 -m pylint -j 0
        language: system
        types: [python]
        files: ^pyisyox/.+\.py$
        args: ["-rn", "-sn"]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        files: ^pyisyox\/.+.py$
